version: '3.1'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: unless-stopped
    ports:
      - 4000:4000


volumes:
  db-data:
    driver: local
